### ISSUE TITLE
Syntax error in JS/CSS breaks application.html.haml include

### ISSUE THREAD

**Issue by robwagner33** [VentApp/vent-rails#1]
**Summary:**

There appears to be a syntax error in one or multiple of the included JS or CSS files. The HAML syntax is fine.

**Error:**

SyntaxError: [stdin]:2:1: unexpected indentation

**Repeating:**

1. Boot the app
2. Navigate to home page

**Comment by petitJAM** [comment]
Yea, we used a rails new generator gem https://github.com/tenforwardconsulting/sagacious_succotash/ to set up.  There's a bug where it didn't convert the project name correctly

[`window.Vent-rails = {};`](https://github.com/VentApp/vent-rails/blob/master/app/assets/javascripts/application.js#L18) is the offending line.  I think @Whiteaj36 fixed it already on his machine. Or I did, idk.

**Comment by robwagner33** [comment]
Coolio, we just need someone to pop in that fix in devel and I'll close the issue.

**Comment by Whiteaj36** [comment]
I'll take that. Should get done next week lol

**Comment by Whiteaj36** [comment]
Next week, next month+2 weeks. I think we've found our scoping multiplier.
